# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/austin01/vivado/rtl_kernel_wizard_0_ex/rtl_kernel_wizard_0_ex.srcs/sources_1/ip/ResultsFIFO/ResultsFIFO.xci
# IP: The module: 'ResultsFIFO' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/austin01/vivado/rtl_kernel_wizard_0_ex/rtl_kernel_wizard_0_ex.gen/sources_1/ip/ResultsFIFO/ResultsFIFO.xdc
# XDC: The top module name and the constraint reference have the same name: 'ResultsFIFO'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/austin01/vivado/rtl_kernel_wizard_0_ex/rtl_kernel_wizard_0_ex.gen/sources_1/ip/ResultsFIFO/ResultsFIFO_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ResultsFIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/austin01/vivado/rtl_kernel_wizard_0_ex/rtl_kernel_wizard_0_ex.gen/sources_1/ip/ResultsFIFO/ResultsFIFO_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ResultsFIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/austin01/vivado/rtl_kernel_wizard_0_ex/rtl_kernel_wizard_0_ex.srcs/sources_1/ip/ResultsFIFO/ResultsFIFO.xci
# IP: The module: 'ResultsFIFO' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/austin01/vivado/rtl_kernel_wizard_0_ex/rtl_kernel_wizard_0_ex.gen/sources_1/ip/ResultsFIFO/ResultsFIFO.xdc
# XDC: The top module name and the constraint reference have the same name: 'ResultsFIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/austin01/vivado/rtl_kernel_wizard_0_ex/rtl_kernel_wizard_0_ex.gen/sources_1/ip/ResultsFIFO/ResultsFIFO_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ResultsFIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/austin01/vivado/rtl_kernel_wizard_0_ex/rtl_kernel_wizard_0_ex.gen/sources_1/ip/ResultsFIFO/ResultsFIFO_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ResultsFIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
