


///////////////////////////////////////////////////////////////////////////
//NOTE: This file has been automatically generated by Vivado.
///////////////////////////////////////////////////////////////////////////
`timescale 1ps/1ps
package axisddrin_vip_pkg;
import axi4stream_vip_pkg::*;
///////////////////////////////////////////////////////////////////////////
// These parameters are named after the component for use in your verification 
// environment.
///////////////////////////////////////////////////////////////////////////
      parameter axisddrin_vip_VIP_INTERFACE_MODE     = 0;
      parameter axisddrin_vip_VIP_SIGNAL_SET         = 8'b00011011;
      parameter axisddrin_vip_VIP_DATA_WIDTH         = 512;
      parameter axisddrin_vip_VIP_ID_WIDTH           = 1;
      parameter axisddrin_vip_VIP_DEST_WIDTH         = 1;
      parameter axisddrin_vip_VIP_USER_WIDTH         = 0;
      parameter axisddrin_vip_VIP_USER_BITS_PER_BYTE = 0;
      parameter axisddrin_vip_VIP_HAS_TREADY         = 1;
      parameter axisddrin_vip_VIP_HAS_TSTRB          = 0;
      parameter axisddrin_vip_VIP_HAS_TKEEP          = 1;
      parameter axisddrin_vip_VIP_HAS_TLAST          = 1;
      parameter axisddrin_vip_VIP_HAS_ACLKEN         = 0;
      parameter axisddrin_vip_VIP_HAS_ARESETN        = 1;
///////////////////////////////////////////////////////////////////////////
typedef axi4stream_mst_agent #(axisddrin_vip_VIP_SIGNAL_SET, 
                        axisddrin_vip_VIP_DEST_WIDTH,
                        axisddrin_vip_VIP_DATA_WIDTH,
                        axisddrin_vip_VIP_ID_WIDTH,
                        axisddrin_vip_VIP_USER_WIDTH, 
                        axisddrin_vip_VIP_USER_BITS_PER_BYTE,
                        axisddrin_vip_VIP_HAS_ARESETN) axisddrin_vip_mst_t;
      
///////////////////////////////////////////////////////////////////////////
// How to start the verification component
///////////////////////////////////////////////////////////////////////////
//      axisddrin_vip_mst_t  axisddrin_vip_mst;
//      initial begin : START_axisddrin_vip_MASTER
//        axisddrin_vip_mst = new("axisddrin_vip_mst", `axisddrin_vip_PATH_TO_INTERFACE);
//        axisddrin_vip_mst.start_master();
//      end



endpackage : axisddrin_vip_pkg
