#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("axisHBMin_TDATA", 256, hls_in, 2, "axis", "in_data", 1),
	Port_Property("axisHBMin_TVALID", 1, hls_in, 5, "axis", "in_vld", 1),
	Port_Property("axisHBMin_TREADY", 1, hls_out, 5, "axis", "in_acc", 1),
	Port_Property("axisHBMin_TKEEP", 32, hls_in, 3, "axis", "in_data", 1),
	Port_Property("axisHBMin_TSTRB", 32, hls_in, 4, "axis", "in_data", 1),
	Port_Property("axisHBMin_TLAST", 1, hls_in, 5, "axis", "in_data", 1),
	Port_Property("axisDDRin_TDATA", 512, hls_in, 6, "axis", "in_data", 1),
	Port_Property("axisDDRin_TVALID", 1, hls_in, 9, "axis", "in_vld", 1),
	Port_Property("axisDDRin_TREADY", 1, hls_out, 9, "axis", "in_acc", 1),
	Port_Property("axisDDRin_TKEEP", 64, hls_in, 7, "axis", "in_data", 1),
	Port_Property("axisDDRin_TSTRB", 64, hls_in, 8, "axis", "in_data", 1),
	Port_Property("axisDDRin_TLAST", 1, hls_in, 9, "axis", "in_data", 1),
	Port_Property("axisHBMout_TDATA", 256, hls_out, 10, "axis", "out_data", 1),
	Port_Property("axisHBMout_TVALID", 1, hls_out, 13, "axis", "out_vld", 1),
	Port_Property("axisHBMout_TREADY", 1, hls_in, 13, "axis", "out_acc", 1),
	Port_Property("axisHBMout_TKEEP", 32, hls_out, 11, "axis", "out_data", 1),
	Port_Property("axisHBMout_TSTRB", 32, hls_out, 12, "axis", "out_data", 1),
	Port_Property("axisHBMout_TLAST", 1, hls_out, 13, "axis", "out_data", 1),
	Port_Property("axisDDRout_TDATA", 512, hls_out, 14, "axis", "out_data", 1),
	Port_Property("axisDDRout_TVALID", 1, hls_out, 17, "axis", "out_vld", 1),
	Port_Property("axisDDRout_TREADY", 1, hls_in, 17, "axis", "out_acc", 1),
	Port_Property("axisDDRout_TKEEP", 64, hls_out, 15, "axis", "out_data", 1),
	Port_Property("axisDDRout_TSTRB", 64, hls_out, 16, "axis", "out_data", 1),
	Port_Property("axisDDRout_TLAST", 1, hls_out, 17, "axis", "out_data", 1),
	Port_Property("s_axi_control_AWVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_AWREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_AWADDR", 6, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_WVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_WREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_WDATA", 32, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_WSTRB", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_ARVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_ARREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_ARADDR", 6, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_RVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_RREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_RDATA", 32, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_RRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_BVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_BREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_BRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("interrupt", 1, hls_out, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "rtl_kernel_wizard_0";
