#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu May 02 20:50:11 PDT 2024
# SW Build 3526262 on Mon Apr 18 15:47:01 MDT 2022
#
# IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_top_kernel_behav -key {Behavioral:sim_1:Functional:tb_top_kernel} -tclbatch tb_top_kernel.tcl -protoinst "protoinst_files/VMU_FIFOs.protoinst" -protoinst "protoinst_files/PE_IPs.protoinst" -protoinst "protoinst_files/bd_d1ca.protoinst" -protoinst "protoinst_files/MemoryInterfacesVIP.protoinst" -view /home/austin01/vivado/rtl_kernel_wizard_0_ex/tb_top_kernel_behav.wcfg -log simulate.log -sv_seed 1"
xsim tb_top_kernel_behav -key {Behavioral:sim_1:Functional:tb_top_kernel} -tclbatch tb_top_kernel.tcl -protoinst "protoinst_files/VMU_FIFOs.protoinst" -protoinst "protoinst_files/PE_IPs.protoinst" -protoinst "protoinst_files/bd_d1ca.protoinst" -protoinst "protoinst_files/MemoryInterfacesVIP.protoinst" -view /home/austin01/vivado/rtl_kernel_wizard_0_ex/tb_top_kernel_behav.wcfg -log simulate.log -sv_seed 1

