# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/austin01/vivado/rtl_kernel_wizard_0_ex/rtl_kernel_wizard_0_ex.srcs/sources_1/ip/LoadVerticesFIFO/LoadVerticesFIFO.xci
# IP: The module: 'LoadVerticesFIFO' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/austin01/vivado/rtl_kernel_wizard_0_ex/rtl_kernel_wizard_0_ex.gen/sources_1/ip/LoadVerticesFIFO/LoadVerticesFIFO.xdc
# XDC: The top module name and the constraint reference have the same name: 'LoadVerticesFIFO'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/austin01/vivado/rtl_kernel_wizard_0_ex/rtl_kernel_wizard_0_ex.gen/sources_1/ip/LoadVerticesFIFO/LoadVerticesFIFO_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'LoadVerticesFIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/austin01/vivado/rtl_kernel_wizard_0_ex/rtl_kernel_wizard_0_ex.gen/sources_1/ip/LoadVerticesFIFO/LoadVerticesFIFO_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'LoadVerticesFIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/austin01/vivado/rtl_kernel_wizard_0_ex/rtl_kernel_wizard_0_ex.srcs/sources_1/ip/LoadVerticesFIFO/LoadVerticesFIFO.xci
# IP: The module: 'LoadVerticesFIFO' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/austin01/vivado/rtl_kernel_wizard_0_ex/rtl_kernel_wizard_0_ex.gen/sources_1/ip/LoadVerticesFIFO/LoadVerticesFIFO.xdc
# XDC: The top module name and the constraint reference have the same name: 'LoadVerticesFIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/austin01/vivado/rtl_kernel_wizard_0_ex/rtl_kernel_wizard_0_ex.gen/sources_1/ip/LoadVerticesFIFO/LoadVerticesFIFO_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'LoadVerticesFIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/austin01/vivado/rtl_kernel_wizard_0_ex/rtl_kernel_wizard_0_ex.gen/sources_1/ip/LoadVerticesFIFO/LoadVerticesFIFO_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'LoadVerticesFIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
