# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/austin01/vivado/rtl_kernel_wizard_0_ex/imports/rtl_kernel_wizard_0_user.xdc

# Block Designs: bd/VMU_FIFOs/VMU_FIFOs.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==VMU_FIFOs || ORIG_REF_NAME==VMU_FIFOs} -quiet] -quiet

# IP: bd/VMU_FIFOs/ip/VMU_FIFOs_fifo_generator_0_0/VMU_FIFOs_fifo_generator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==VMU_FIFOs_fifo_generator_0_0 || ORIG_REF_NAME==VMU_FIFOs_fifo_generator_0_0} -quiet] -quiet

# Block Designs: bd/PE_IPs/PE_IPs.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PE_IPs || ORIG_REF_NAME==PE_IPs} -quiet] -quiet

# IP: bd/PE_IPs/ip/PE_IPs_blk_mem_gen_0_0/PE_IPs_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PE_IPs_blk_mem_gen_0_0 || ORIG_REF_NAME==PE_IPs_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/PE_IPs/ip/PE_IPs_blk_mem_gen_0_1/PE_IPs_blk_mem_gen_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PE_IPs_blk_mem_gen_0_1 || ORIG_REF_NAME==PE_IPs_blk_mem_gen_0_1} -quiet] -quiet

# IP: bd/PE_IPs/ip/PE_IPs_blk_mem_gen_0_2/PE_IPs_blk_mem_gen_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PE_IPs_blk_mem_gen_0_2 || ORIG_REF_NAME==PE_IPs_blk_mem_gen_0_2} -quiet] -quiet

# IP: bd/PE_IPs/ip/PE_IPs_fifo_generator_0_0/PE_IPs_fifo_generator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PE_IPs_fifo_generator_0_0 || ORIG_REF_NAME==PE_IPs_fifo_generator_0_0} -quiet] -quiet

# IP: bd/PE_IPs/ip/PE_IPs_Msg_FIFO_Out_0/PE_IPs_Msg_FIFO_Out_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PE_IPs_Msg_FIFO_Out_0 || ORIG_REF_NAME==PE_IPs_Msg_FIFO_Out_0} -quiet] -quiet

# IP: bd/PE_IPs/ip/PE_IPs_Msg_FIFO_In_0/PE_IPs_Msg_FIFO_In_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PE_IPs_Msg_FIFO_In_0 || ORIG_REF_NAME==PE_IPs_Msg_FIFO_In_0} -quiet] -quiet

# IP: bd/PE_IPs/ip/PE_IPs_Msg_FIFO_In_1/PE_IPs_Msg_FIFO_In_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PE_IPs_Msg_FIFO_In_1 || ORIG_REF_NAME==PE_IPs_Msg_FIFO_In_1} -quiet] -quiet

# XDC: /home/austin01/vivado/rtl_kernel_wizard_0_ex/rtl_kernel_wizard_0_ex.gen/sources_1/bd/VMU_FIFOs/VMU_FIFOs_ooc.xdc

# XDC: /home/austin01/vivado/rtl_kernel_wizard_0_ex/rtl_kernel_wizard_0_ex.gen/sources_1/bd/PE_IPs/PE_IPs_ooc.xdc
