#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2022.1 (64-bit)
#
# Filename    : MemoryInterfacesVIP.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Tue Apr 30 23:39:23 PDT 2024
# SW Build 3526262 on Mon Apr 18 15:47:01 MDT 2022
#
# Tool Version Limit: 2022.04 
#
# usage: MemoryInterfacesVIP.sh [-help]
# usage: MemoryInterfacesVIP.sh [-lib_map_path]
# usage: MemoryInterfacesVIP.sh [-noclean_files]
# usage: MemoryInterfacesVIP.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'MemoryInterfacesVIP.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Set vlogan compile options
vlogan_opts="-full64"

# Set vhdlan compile options
vhdlan_opts="-full64"

# Set vcs elaboration options
vcs_elab_opts="-full64 -debug_acc+pp+dmptf -t ps -licqueue -l elaborate.log"

# Set vcs simulation options
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xpm axi_infrastructure_v1_1_0 xil_defaultlib axi_vip_v1_1_12 xlconstant_v1_1_7 lib_cdc_v1_0_2 proc_sys_reset_v5_0_13 smartconnect_v1_0 axi_register_slice_v2_1_26)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "MemoryInterfacesVIP.sh - Script generated by export_simulation (Vivado v2022.1 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "/home/austin01/Xilinx/Vivado/2022.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/home/austin01/Xilinx/Vivado/2022.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
    "/home/austin01/Xilinx/Vivado/2022.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/home/austin01/Xilinx/Vivado/2022.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_axi_vip_0_0/sim/MemoryInterfacesVIP_axi_vip_0_0_pkg.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_12 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/1033/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_axi_vip_0_0/sim/MemoryInterfacesVIP_axi_vip_0_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_HBMVIP_0/sim/MemoryInterfacesVIP_HBMVIP_0_pkg.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_HBMVIP_0/sim/MemoryInterfacesVIP_HBMVIP_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ipshared/33b0/rd_engine.v" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ipshared/33b0/wr_engine.v" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ipshared/33b0/axi_engine.v" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_DDR_00_AXI_Engine_0/sim/MemoryInterfacesVIP_DDR_00_AXI_Engine_0.v" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_HBM_00_AXI_Engine_0/sim/MemoryInterfacesVIP_HBM_00_AXI_Engine_0.v" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/sim/MemoryInterfacesVIP.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_HBMVIP_2/sim/MemoryInterfacesVIP_HBMVIP_2_pkg.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_HBMVIP_2/sim/MemoryInterfacesVIP_HBMVIP_2.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_HBM_00_AXI_Engine_2/sim/MemoryInterfacesVIP_HBM_00_AXI_Engine_2.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_HBMVIP_3/sim/MemoryInterfacesVIP_HBMVIP_3_pkg.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_HBMVIP_3/sim/MemoryInterfacesVIP_HBMVIP_3.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_HBM_00_AXI_Engine_3/sim/MemoryInterfacesVIP_HBM_00_AXI_Engine_3.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_HBMVIP_4/sim/MemoryInterfacesVIP_HBMVIP_4_pkg.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_HBMVIP_4/sim/MemoryInterfacesVIP_HBMVIP_4.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_HBM_00_AXI_Engine_4/sim/MemoryInterfacesVIP_HBM_00_AXI_Engine_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_HBMVIP_5/sim/MemoryInterfacesVIP_HBMVIP_5_pkg.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_HBMVIP_5/sim/MemoryInterfacesVIP_HBMVIP_5.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_HBM_00_AXI_Engine_5/sim/MemoryInterfacesVIP_HBM_00_AXI_Engine_5.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_HBMVIP_6/sim/MemoryInterfacesVIP_HBMVIP_6_pkg.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_HBMVIP_6/sim/MemoryInterfacesVIP_HBMVIP_6.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_HBM_00_AXI_Engine_6/sim/MemoryInterfacesVIP_HBM_00_AXI_Engine_6.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_HBMVIP_7/sim/MemoryInterfacesVIP_HBMVIP_7_pkg.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_HBMVIP_7/sim/MemoryInterfacesVIP_HBMVIP_7.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_HBM_00_AXI_Engine_7/sim/MemoryInterfacesVIP_HBM_00_AXI_Engine_7.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_HBMVIP_8/sim/MemoryInterfacesVIP_HBMVIP_8_pkg.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_HBMVIP_8/sim/MemoryInterfacesVIP_HBMVIP_8.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_HBM_00_AXI_Engine_8/sim/MemoryInterfacesVIP_HBM_00_AXI_Engine_8.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_HBMVIP_9/sim/MemoryInterfacesVIP_HBMVIP_9_pkg.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_HBMVIP_9/sim/MemoryInterfacesVIP_HBMVIP_9.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_HBM_00_AXI_Engine_9/sim/MemoryInterfacesVIP_HBM_00_AXI_Engine_9.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_HBMVIP_10/sim/MemoryInterfacesVIP_HBMVIP_10_pkg.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_HBMVIP_10/sim/MemoryInterfacesVIP_HBMVIP_10.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_HBM_00_AXI_Engine_10/sim/MemoryInterfacesVIP_HBM_00_AXI_Engine_10.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_HBMVIP_11/sim/MemoryInterfacesVIP_HBMVIP_11_pkg.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_HBMVIP_11/sim/MemoryInterfacesVIP_HBMVIP_11.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_HBM_00_AXI_Engine_11/sim/MemoryInterfacesVIP_HBM_00_AXI_Engine_11.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_HBMVIP_12/sim/MemoryInterfacesVIP_HBMVIP_12_pkg.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_HBMVIP_12/sim/MemoryInterfacesVIP_HBMVIP_12.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_HBM_00_AXI_Engine_12/sim/MemoryInterfacesVIP_HBM_00_AXI_Engine_12.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_HBMVIP0_0/sim/MemoryInterfacesVIP_HBMVIP0_0_pkg.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_HBMVIP0_0/sim/MemoryInterfacesVIP_HBMVIP0_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_HBM_00_AXI_Engine_13/sim/MemoryInterfacesVIP_HBM_00_AXI_Engine_13.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_HBMVIP0_1/sim/MemoryInterfacesVIP_HBMVIP0_1_pkg.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_HBMVIP0_1/sim/MemoryInterfacesVIP_HBMVIP0_1.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_HBM_00_AXI_Engine_14/sim/MemoryInterfacesVIP_HBM_00_AXI_Engine_14.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_HBMVIP0_2/sim/MemoryInterfacesVIP_HBMVIP0_2_pkg.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_HBMVIP0_2/sim/MemoryInterfacesVIP_HBMVIP0_2.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_HBM_00_AXI_Engine_15/sim/MemoryInterfacesVIP_HBM_00_AXI_Engine_15.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_HBMVIP0_3/sim/MemoryInterfacesVIP_HBMVIP0_3_pkg.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_HBMVIP0_3/sim/MemoryInterfacesVIP_HBMVIP0_3.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_HBM_00_AXI_Engine_16/sim/MemoryInterfacesVIP_HBM_00_AXI_Engine_16.v" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_DDR_00_AXI_Engine_1/sim/MemoryInterfacesVIP_DDR_00_AXI_Engine_1.v" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_DDR_00_AXI_Engine_2/sim/MemoryInterfacesVIP_DDR_00_AXI_Engine_2.v" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_DDR_00_AXI_Engine_3/sim/MemoryInterfacesVIP_DDR_00_AXI_Engine_3.v" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_DDR_00_AXI_Engine_4/sim/MemoryInterfacesVIP_DDR_00_AXI_Engine_4.v" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_DDR_00_AXI_Engine_5/sim/MemoryInterfacesVIP_DDR_00_AXI_Engine_5.v" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_DDR_00_AXI_Engine_6/sim/MemoryInterfacesVIP_DDR_00_AXI_Engine_6.v" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_DDR_00_AXI_Engine_7/sim/MemoryInterfacesVIP_DDR_00_AXI_Engine_7.v" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_DDR_00_AXI_Engine_8/sim/MemoryInterfacesVIP_DDR_00_AXI_Engine_8.v" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_DDR_00_AXI_Engine_9/sim/MemoryInterfacesVIP_DDR_00_AXI_Engine_9.v" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_DDR_00_AXI_Engine_10/sim/MemoryInterfacesVIP_DDR_00_AXI_Engine_10.v" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_DDR_00_AXI_Engine_11/sim/MemoryInterfacesVIP_DDR_00_AXI_Engine_11.v" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_DDR_00_AXI_Engine_12/sim/MemoryInterfacesVIP_DDR_00_AXI_Engine_12.v" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_DDR_00_AXI_Engine_13/sim/MemoryInterfacesVIP_DDR_00_AXI_Engine_13.v" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_DDR_00_AXI_Engine_14/sim/MemoryInterfacesVIP_DDR_00_AXI_Engine_14.v" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_DDR_00_AXI_Engine_15/sim/MemoryInterfacesVIP_DDR_00_AXI_Engine_15.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/fcfc/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_0/sim/bd_d1ca_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_1/sim/bd_d1ca_psr_aclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv" \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/c012/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_2/sim/bd_d1ca_arsw_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_3/sim/bd_d1ca_rsw_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_4/sim/bd_d1ca_awsw_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_5/sim/bd_d1ca_wsw_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_6/sim/bd_d1ca_bsw_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ea34/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_7/sim/bd_d1ca_s00mmu_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/4fd2/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_8/sim/bd_d1ca_s00tr_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/8047/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_9/sim/bd_d1ca_s00sic_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f38e/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_10/sim/bd_d1ca_s00a2s_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_11/sim/bd_d1ca_sarn_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_12/sim/bd_d1ca_srn_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_13/sim/bd_d1ca_sawn_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_14/sim/bd_d1ca_swn_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_15/sim/bd_d1ca_sbn_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_16/sim/bd_d1ca_s01mmu_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_17/sim/bd_d1ca_s01tr_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_18/sim/bd_d1ca_s01sic_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_19/sim/bd_d1ca_s01a2s_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_20/sim/bd_d1ca_sarn_1.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_21/sim/bd_d1ca_srn_1.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_22/sim/bd_d1ca_sawn_1.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_23/sim/bd_d1ca_swn_1.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_24/sim/bd_d1ca_sbn_1.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_25/sim/bd_d1ca_s02mmu_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_26/sim/bd_d1ca_s02tr_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_27/sim/bd_d1ca_s02sic_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_28/sim/bd_d1ca_s02a2s_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_29/sim/bd_d1ca_sarn_2.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_30/sim/bd_d1ca_srn_2.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_31/sim/bd_d1ca_sawn_2.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_32/sim/bd_d1ca_swn_2.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_33/sim/bd_d1ca_sbn_2.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_34/sim/bd_d1ca_s03mmu_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_35/sim/bd_d1ca_s03tr_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_36/sim/bd_d1ca_s03sic_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_37/sim/bd_d1ca_s03a2s_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_38/sim/bd_d1ca_sarn_3.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_39/sim/bd_d1ca_srn_3.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_40/sim/bd_d1ca_sawn_3.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_41/sim/bd_d1ca_swn_3.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_42/sim/bd_d1ca_sbn_3.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_43/sim/bd_d1ca_s04mmu_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_44/sim/bd_d1ca_s04tr_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_45/sim/bd_d1ca_s04sic_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_46/sim/bd_d1ca_s04a2s_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_47/sim/bd_d1ca_sarn_4.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_48/sim/bd_d1ca_srn_4.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_49/sim/bd_d1ca_sawn_4.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_50/sim/bd_d1ca_swn_4.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_51/sim/bd_d1ca_sbn_4.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_52/sim/bd_d1ca_s05mmu_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_53/sim/bd_d1ca_s05tr_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_54/sim/bd_d1ca_s05sic_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_55/sim/bd_d1ca_s05a2s_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_56/sim/bd_d1ca_sarn_5.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_57/sim/bd_d1ca_srn_5.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_58/sim/bd_d1ca_sawn_5.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_59/sim/bd_d1ca_swn_5.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_60/sim/bd_d1ca_sbn_5.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_61/sim/bd_d1ca_s06mmu_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_62/sim/bd_d1ca_s06tr_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_63/sim/bd_d1ca_s06sic_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_64/sim/bd_d1ca_s06a2s_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_65/sim/bd_d1ca_sarn_6.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_66/sim/bd_d1ca_srn_6.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_67/sim/bd_d1ca_sawn_6.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_68/sim/bd_d1ca_swn_6.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_69/sim/bd_d1ca_sbn_6.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_70/sim/bd_d1ca_s07mmu_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_71/sim/bd_d1ca_s07tr_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_72/sim/bd_d1ca_s07sic_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_73/sim/bd_d1ca_s07a2s_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_74/sim/bd_d1ca_sarn_7.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_75/sim/bd_d1ca_srn_7.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_76/sim/bd_d1ca_sawn_7.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_77/sim/bd_d1ca_swn_7.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_78/sim/bd_d1ca_sbn_7.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_79/sim/bd_d1ca_s08mmu_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_80/sim/bd_d1ca_s08tr_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_81/sim/bd_d1ca_s08sic_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_82/sim/bd_d1ca_s08a2s_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_83/sim/bd_d1ca_sarn_8.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_84/sim/bd_d1ca_srn_8.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_85/sim/bd_d1ca_sawn_8.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_86/sim/bd_d1ca_swn_8.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_87/sim/bd_d1ca_sbn_8.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_88/sim/bd_d1ca_s09mmu_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_89/sim/bd_d1ca_s09tr_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_90/sim/bd_d1ca_s09sic_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_91/sim/bd_d1ca_s09a2s_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_92/sim/bd_d1ca_sarn_9.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_93/sim/bd_d1ca_srn_9.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_94/sim/bd_d1ca_sawn_9.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_95/sim/bd_d1ca_swn_9.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_96/sim/bd_d1ca_sbn_9.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_97/sim/bd_d1ca_s10mmu_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_98/sim/bd_d1ca_s10tr_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_99/sim/bd_d1ca_s10sic_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_100/sim/bd_d1ca_s10a2s_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_101/sim/bd_d1ca_sarn_10.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_102/sim/bd_d1ca_srn_10.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_103/sim/bd_d1ca_sawn_10.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_104/sim/bd_d1ca_swn_10.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_105/sim/bd_d1ca_sbn_10.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_106/sim/bd_d1ca_s11mmu_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_107/sim/bd_d1ca_s11tr_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_108/sim/bd_d1ca_s11sic_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_109/sim/bd_d1ca_s11a2s_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_110/sim/bd_d1ca_sarn_11.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_111/sim/bd_d1ca_srn_11.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_112/sim/bd_d1ca_sawn_11.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_113/sim/bd_d1ca_swn_11.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_114/sim/bd_d1ca_sbn_11.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_115/sim/bd_d1ca_s12mmu_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_116/sim/bd_d1ca_s12tr_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_117/sim/bd_d1ca_s12sic_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_118/sim/bd_d1ca_s12a2s_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_119/sim/bd_d1ca_sarn_12.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_120/sim/bd_d1ca_srn_12.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_121/sim/bd_d1ca_sawn_12.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_122/sim/bd_d1ca_swn_12.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_123/sim/bd_d1ca_sbn_12.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_124/sim/bd_d1ca_s13mmu_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_125/sim/bd_d1ca_s13tr_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_126/sim/bd_d1ca_s13sic_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_127/sim/bd_d1ca_s13a2s_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_128/sim/bd_d1ca_sarn_13.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_129/sim/bd_d1ca_srn_13.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_130/sim/bd_d1ca_sawn_13.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_131/sim/bd_d1ca_swn_13.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_132/sim/bd_d1ca_sbn_13.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_133/sim/bd_d1ca_s14mmu_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_134/sim/bd_d1ca_s14tr_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_135/sim/bd_d1ca_s14sic_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_136/sim/bd_d1ca_s14a2s_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_137/sim/bd_d1ca_sarn_14.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_138/sim/bd_d1ca_srn_14.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_139/sim/bd_d1ca_sawn_14.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_140/sim/bd_d1ca_swn_14.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_141/sim/bd_d1ca_sbn_14.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_142/sim/bd_d1ca_s15mmu_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_143/sim/bd_d1ca_s15tr_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_144/sim/bd_d1ca_s15sic_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_145/sim/bd_d1ca_s15a2s_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_146/sim/bd_d1ca_sarn_15.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_147/sim/bd_d1ca_srn_15.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_148/sim/bd_d1ca_sawn_15.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_149/sim/bd_d1ca_swn_15.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_150/sim/bd_d1ca_sbn_15.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/9cc5/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_151/sim/bd_d1ca_m00s2a_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_152/sim/bd_d1ca_m00arn_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_153/sim/bd_d1ca_m00rn_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_154/sim/bd_d1ca_m00awn_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_155/sim/bd_d1ca_m00wn_0.sv" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_156/sim/bd_d1ca_m00bn_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/6bba/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/ip/ip_157/sim/bd_d1ca_m00e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/bd_0/sim/bd_d1ca.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_26 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/0a3f/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../rtl_kernel_wizard_0_ex.gen/sim_1/bd/MemoryInterfacesVIP/ipshared/66be/hdl/verilog" +incdir+"/home/austin01/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/MemoryInterfacesVIP/ip/MemoryInterfacesVIP_smartconnect_0_0/sim/MemoryInterfacesVIP_smartconnect_0_0.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log
}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.MemoryInterfacesVIP xil_defaultlib.glbl -o MemoryInterfacesVIP_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./MemoryInterfacesVIP_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./MemoryInterfacesVIP.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  else
    lib_map_path="/home/austin01/vivado/rtl_kernel_wizard_0_ex/rtl_kernel_wizard_0_ex.cache/compile_simlib/vcs"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key MemoryInterfacesVIP_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc MemoryInterfacesVIP_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./MemoryInterfacesVIP.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: MemoryInterfacesVIP.sh [-help]\n\
Usage: MemoryInterfacesVIP.sh [-lib_map_path]\n\
Usage: MemoryInterfacesVIP.sh [-reset_run]\n\
Usage: MemoryInterfacesVIP.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
