# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/austin01/vivado/rtl_kernel_wizard_0_ex/rtl_kernel_wizard_0_ex.srcs/sources_1/bd/MemoryInterfaces/ip/MemoryInterfaces_hbm_0_0_1/MemoryInterfaces_hbm_0_0.xci
# IP: The module: 'MemoryInterfaces_hbm_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/austin01/vivado/rtl_kernel_wizard_0_ex/rtl_kernel_wizard_0_ex.gen/sources_1/bd/MemoryInterfaces/ip/MemoryInterfaces_hbm_0_0_1/hdl/par/hbm_ip.xdc
# XDC: The top module name and the constraint reference have the same name: 'MemoryInterfaces_hbm_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/austin01/vivado/rtl_kernel_wizard_0_ex/rtl_kernel_wizard_0_ex.gen/sources_1/bd/MemoryInterfaces/ip/MemoryInterfaces_hbm_0_0_1/hdl/par/MemoryInterfaces_hbm_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MemoryInterfaces_hbm_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/austin01/vivado/rtl_kernel_wizard_0_ex/rtl_kernel_wizard_0_ex.srcs/sources_1/bd/MemoryInterfaces/ip/MemoryInterfaces_hbm_0_0_1/MemoryInterfaces_hbm_0_0.xci
# IP: The module: 'MemoryInterfaces_hbm_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/austin01/vivado/rtl_kernel_wizard_0_ex/rtl_kernel_wizard_0_ex.gen/sources_1/bd/MemoryInterfaces/ip/MemoryInterfaces_hbm_0_0_1/hdl/par/hbm_ip.xdc
# XDC: The top module name and the constraint reference have the same name: 'MemoryInterfaces_hbm_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/austin01/vivado/rtl_kernel_wizard_0_ex/rtl_kernel_wizard_0_ex.gen/sources_1/bd/MemoryInterfaces/ip/MemoryInterfaces_hbm_0_0_1/hdl/par/MemoryInterfaces_hbm_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MemoryInterfaces_hbm_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
