-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity rtl_kernel_wizard_0_rtl_kernel_wizard_0_Pipeline_VITIS_LOOP_96_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    axisHBMin_TVALID : IN STD_LOGIC;
    axisHBMout_TREADY : IN STD_LOGIC;
    axisHBMin_TDATA : IN STD_LOGIC_VECTOR (255 downto 0);
    axisHBMin_TREADY : OUT STD_LOGIC;
    axisHBMin_TKEEP : IN STD_LOGIC_VECTOR (31 downto 0);
    axisHBMin_TSTRB : IN STD_LOGIC_VECTOR (31 downto 0);
    axisHBMin_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    axisHBMout_TDATA : OUT STD_LOGIC_VECTOR (255 downto 0);
    axisHBMout_TVALID : OUT STD_LOGIC;
    axisHBMout_TKEEP : OUT STD_LOGIC_VECTOR (31 downto 0);
    axisHBMout_TSTRB : OUT STD_LOGIC_VECTOR (31 downto 0);
    axisHBMout_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of rtl_kernel_wizard_0_rtl_kernel_wizard_0_Pipeline_VITIS_LOOP_96_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_5F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv32_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000000";
    constant ap_const_lv32_9F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011111";
    constant ap_const_lv32_A0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100000";
    constant ap_const_lv32_BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111111";
    constant ap_const_lv32_C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000000";
    constant ap_const_lv32_DF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011111";
    constant ap_const_lv32_E0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100000";
    constant ap_const_lv32_FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111111";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal tmp_last_V_fu_114_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal axisHBMin_TDATA_blk_n : STD_LOGIC;
    signal axisHBMout_TDATA_blk_n : STD_LOGIC;
    signal trunc_ln674_fu_119_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_s_fu_129_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_2_fu_145_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_3_fu_161_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_1_fu_177_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_4_fu_193_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_6_fu_209_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_7_fu_225_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln232_7_fu_235_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln232_6_fu_219_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln232_5_fu_203_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln232_4_fu_187_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln232_3_fu_171_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln232_2_fu_155_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln232_1_fu_139_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln232_fu_123_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_loop_init : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component rtl_kernel_wizard_0_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component rtl_kernel_wizard_0_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((axisHBMout_TREADY = ap_const_logic_0) or (axisHBMin_TVALID = ap_const_logic_0) or (ap_start_int = ap_const_logic_0))) and (ap_loop_exit_ready = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, axisHBMin_TVALID, axisHBMout_TREADY, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln232_1_fu_139_p2 <= std_logic_vector(unsigned(p_Result_s_fu_129_p4) + unsigned(ap_const_lv32_1));
    add_ln232_2_fu_155_p2 <= std_logic_vector(unsigned(p_Result_2_fu_145_p4) + unsigned(ap_const_lv32_1));
    add_ln232_3_fu_171_p2 <= std_logic_vector(unsigned(p_Result_3_fu_161_p4) + unsigned(ap_const_lv32_1));
    add_ln232_4_fu_187_p2 <= std_logic_vector(unsigned(p_Result_1_fu_177_p4) + unsigned(ap_const_lv32_1));
    add_ln232_5_fu_203_p2 <= std_logic_vector(unsigned(p_Result_4_fu_193_p4) + unsigned(ap_const_lv32_1));
    add_ln232_6_fu_219_p2 <= std_logic_vector(unsigned(p_Result_6_fu_209_p4) + unsigned(ap_const_lv32_1));
    add_ln232_7_fu_235_p2 <= std_logic_vector(unsigned(p_Result_7_fu_225_p4) + unsigned(ap_const_lv32_1));
    add_ln232_fu_123_p2 <= std_logic_vector(unsigned(trunc_ln674_fu_119_p1) + unsigned(ap_const_lv32_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(axisHBMin_TVALID, axisHBMout_TREADY, ap_start_int)
    begin
        if (((axisHBMout_TREADY = ap_const_logic_0) or (axisHBMin_TVALID = ap_const_logic_0) or (ap_start_int = ap_const_logic_0))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(axisHBMin_TVALID, axisHBMout_TREADY, ap_start_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((axisHBMout_TREADY = ap_const_logic_0) or (axisHBMin_TVALID = ap_const_logic_0) or (ap_start_int = ap_const_logic_0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_state1, axisHBMin_TVALID, axisHBMout_TREADY, tmp_last_V_fu_114_p1, ap_start_int)
    begin
        if ((not(((axisHBMout_TREADY = ap_const_logic_0) or (axisHBMin_TVALID = ap_const_logic_0) or (ap_start_int = ap_const_logic_0))) and (tmp_last_V_fu_114_p1 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_state1, axisHBMin_TVALID, axisHBMout_TREADY, ap_loop_exit_ready, ap_done_reg, ap_start_int)
    begin
        if ((not(((axisHBMout_TREADY = ap_const_logic_0) or (axisHBMin_TVALID = ap_const_logic_0) or (ap_start_int = ap_const_logic_0))) and (ap_loop_exit_ready = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_state1, axisHBMin_TVALID, axisHBMout_TREADY, ap_start_int)
    begin
        if ((not(((axisHBMout_TREADY = ap_const_logic_0) or (axisHBMin_TVALID = ap_const_logic_0) or (ap_start_int = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    axisHBMin_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state1, axisHBMin_TVALID, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            axisHBMin_TDATA_blk_n <= axisHBMin_TVALID;
        else 
            axisHBMin_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    axisHBMin_TREADY_assign_proc : process(ap_CS_fsm_state1, axisHBMin_TVALID, axisHBMout_TREADY, ap_start_int)
    begin
        if ((not(((axisHBMout_TREADY = ap_const_logic_0) or (axisHBMin_TVALID = ap_const_logic_0) or (ap_start_int = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            axisHBMin_TREADY <= ap_const_logic_1;
        else 
            axisHBMin_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    axisHBMout_TDATA <= (((((((add_ln232_7_fu_235_p2 & add_ln232_6_fu_219_p2) & add_ln232_5_fu_203_p2) & add_ln232_4_fu_187_p2) & add_ln232_3_fu_171_p2) & add_ln232_2_fu_155_p2) & add_ln232_1_fu_139_p2) & add_ln232_fu_123_p2);

    axisHBMout_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state1, axisHBMout_TREADY, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            axisHBMout_TDATA_blk_n <= axisHBMout_TREADY;
        else 
            axisHBMout_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    axisHBMout_TKEEP <= axisHBMin_TKEEP;
    axisHBMout_TLAST <= axisHBMin_TLAST;
    axisHBMout_TSTRB <= ap_const_lv32_0;

    axisHBMout_TVALID_assign_proc : process(ap_CS_fsm_state1, axisHBMin_TVALID, axisHBMout_TREADY, ap_start_int)
    begin
        if ((not(((axisHBMout_TREADY = ap_const_logic_0) or (axisHBMin_TVALID = ap_const_logic_0) or (ap_start_int = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            axisHBMout_TVALID <= ap_const_logic_1;
        else 
            axisHBMout_TVALID <= ap_const_logic_0;
        end if; 
    end process;

    p_Result_1_fu_177_p4 <= axisHBMin_TDATA(159 downto 128);
    p_Result_2_fu_145_p4 <= axisHBMin_TDATA(95 downto 64);
    p_Result_3_fu_161_p4 <= axisHBMin_TDATA(127 downto 96);
    p_Result_4_fu_193_p4 <= axisHBMin_TDATA(191 downto 160);
    p_Result_6_fu_209_p4 <= axisHBMin_TDATA(223 downto 192);
    p_Result_7_fu_225_p4 <= axisHBMin_TDATA(255 downto 224);
    p_Result_s_fu_129_p4 <= axisHBMin_TDATA(63 downto 32);
    tmp_last_V_fu_114_p1 <= axisHBMin_TLAST;
    trunc_ln674_fu_119_p1 <= axisHBMin_TDATA(32 - 1 downto 0);
end behav;
