


///////////////////////////////////////////////////////////////////////////
//NOTE: This file has been automatically generated by Vivado.
///////////////////////////////////////////////////////////////////////////
`timescale 1ps/1ps
package axishbmin_vip_pkg;
import axi4stream_vip_pkg::*;
///////////////////////////////////////////////////////////////////////////
// These parameters are named after the component for use in your verification 
// environment.
///////////////////////////////////////////////////////////////////////////
      parameter axishbmin_vip_VIP_INTERFACE_MODE     = 0;
      parameter axishbmin_vip_VIP_SIGNAL_SET         = 8'b00011011;
      parameter axishbmin_vip_VIP_DATA_WIDTH         = 256;
      parameter axishbmin_vip_VIP_ID_WIDTH           = 1;
      parameter axishbmin_vip_VIP_DEST_WIDTH         = 1;
      parameter axishbmin_vip_VIP_USER_WIDTH         = 0;
      parameter axishbmin_vip_VIP_USER_BITS_PER_BYTE = 0;
      parameter axishbmin_vip_VIP_HAS_TREADY         = 1;
      parameter axishbmin_vip_VIP_HAS_TSTRB          = 0;
      parameter axishbmin_vip_VIP_HAS_TKEEP          = 1;
      parameter axishbmin_vip_VIP_HAS_TLAST          = 1;
      parameter axishbmin_vip_VIP_HAS_ACLKEN         = 0;
      parameter axishbmin_vip_VIP_HAS_ARESETN        = 1;
///////////////////////////////////////////////////////////////////////////
typedef axi4stream_mst_agent #(axishbmin_vip_VIP_SIGNAL_SET, 
                        axishbmin_vip_VIP_DEST_WIDTH,
                        axishbmin_vip_VIP_DATA_WIDTH,
                        axishbmin_vip_VIP_ID_WIDTH,
                        axishbmin_vip_VIP_USER_WIDTH, 
                        axishbmin_vip_VIP_USER_BITS_PER_BYTE,
                        axishbmin_vip_VIP_HAS_ARESETN) axishbmin_vip_mst_t;
      
///////////////////////////////////////////////////////////////////////////
// How to start the verification component
///////////////////////////////////////////////////////////////////////////
//      axishbmin_vip_mst_t  axishbmin_vip_mst;
//      initial begin : START_axishbmin_vip_MASTER
//        axishbmin_vip_mst = new("axishbmin_vip_mst", `axishbmin_vip_PATH_TO_INTERFACE);
//        axishbmin_vip_mst.start_master();
//      end



endpackage : axishbmin_vip_pkg
