


///////////////////////////////////////////////////////////////////////////
//NOTE: This file has been automatically generated by Vivado.
///////////////////////////////////////////////////////////////////////////
`timescale 1ps/1ps
package axishbmout_vip_pkg;
import axi4stream_vip_pkg::*;
///////////////////////////////////////////////////////////////////////////
// These parameters are named after the component for use in your verification 
// environment.
///////////////////////////////////////////////////////////////////////////
      parameter axishbmout_vip_VIP_INTERFACE_MODE     = 2;
      parameter axishbmout_vip_VIP_SIGNAL_SET         = 8'b00011011;
      parameter axishbmout_vip_VIP_DATA_WIDTH         = 256;
      parameter axishbmout_vip_VIP_ID_WIDTH           = 1;
      parameter axishbmout_vip_VIP_DEST_WIDTH         = 1;
      parameter axishbmout_vip_VIP_USER_WIDTH         = 0;
      parameter axishbmout_vip_VIP_USER_BITS_PER_BYTE = 0;
      parameter axishbmout_vip_VIP_HAS_TREADY         = 1;
      parameter axishbmout_vip_VIP_HAS_TSTRB          = 0;
      parameter axishbmout_vip_VIP_HAS_TKEEP          = 1;
      parameter axishbmout_vip_VIP_HAS_TLAST          = 1;
      parameter axishbmout_vip_VIP_HAS_ACLKEN         = 0;
      parameter axishbmout_vip_VIP_HAS_ARESETN        = 1;
///////////////////////////////////////////////////////////////////////////


typedef axi4stream_slv_agent #(axishbmout_vip_VIP_SIGNAL_SET, 
                        axishbmout_vip_VIP_DEST_WIDTH,
                        axishbmout_vip_VIP_DATA_WIDTH,
                        axishbmout_vip_VIP_ID_WIDTH,
                        axishbmout_vip_VIP_USER_WIDTH, 
                        axishbmout_vip_VIP_USER_BITS_PER_BYTE,
                        axishbmout_vip_VIP_HAS_ARESETN) axishbmout_vip_slv_t;
      
///////////////////////////////////////////////////////////////////////////
// How to start the verification component
///////////////////////////////////////////////////////////////////////////
//      axishbmout_vip_slv_t  axishbmout_vip_slv;
//      initial begin : START_axishbmout_vip_SLAVE
//        axishbmout_vip_slv = new("axishbmout_vip_slv", `axishbmout_vip_PATH_TO_INTERFACE);
//        axishbmout_vip_slv.start_slave();
//      end

endpackage : axishbmout_vip_pkg
